import { Contact, ContactExtData } from "common/models/contact";

export const CONTACT_FORM_FIELDS: readonly (keyof Contact)[] = [
    "firstName",
    "middleName",
    "lastName",
    "type",
    "businessName",
    "email1",
    "email2",
    "phone1",
    "phone2",
    "messager1",
    "messager2",
    "messager3",
    "messager4",
    "ZIP",
    "city",
    "state",
    "streetAddress",
    "mailCity",
    "mailState",
    "mailStreetAddress",
    "mailZIP",
    "dluidfront",
    "dluidback",
    "sex",
    "dl_number",
] as const;

export const CONTACT_EXT_DATA_FORM_FIELDS: readonly (keyof ContactExtData)[] = [
    "Buyer_DL_State",
    "Buyer_Driver_License_Num",
    "Buyer_DL_Exp_Date",
    "Buyer_Sex",
    "Buyer_SS_Number",
    "Buyer_Date_Of_Birth",
    "CoBuyer_DL_State",
    "CoBuyer_Driver_License_Num",
    "CoBuyer_DL_Exp_Date",
    "CoBuyer_Sex",
    "CoBuyer_SS_Number",
    "CoBuyer_Date_Of_Birth",
    "CoBuyer_Emp_Company",
    "CoBuyer_First_Name",
    "CoBuyer_Middle_Name",
    "CoBuyer_Last_Name",
    "Buyer_Emp_Company",
    "Buyer_Emp_Contact",
    "Buyer_Emp_Ext",
    "Buyer_Emp_Phone",
    "CoBuyer_Mailing_Address",
    "CoBuyer_Mailing_State",
    "CoBuyer_Mailing_City",
    "CoBuyer_Mailing_Zip",
    "CoBuyer_Res_Address",
    "CoBuyer_State",
    "CoBuyer_City",
    "CoBuyer_Zip_Code",
    "SALESMAN_ID",
    "PROSPECT1_ID",
    "PROSPECT2_ID",
    "Notes",
] as const;
