export const PERMISSION_KEYS = [
    "uaAddContacts",
    "uaAddCreditsAndFees",
    "uaAddDeals",
    "uaAddExpenses",
    "uaAddInventory",
    "uaAllowBackDatingPayments",
    "uaAllowMobile",
    "uaAllowPartialPayments",
    "uaAllowPaymentCalculator",
    "uaAllowPaymentQuote",
    "uaAllowPrinting",
    "uaAllowReports",
    "uaAllowWeb",
    "uaChangePayments",
    "uaClientAdmin",
    "uaCreateReports",
    "uaCreateUsers",
    "uaDeleteAccounts",
    "uaDeleteContacts",
    "uaDeleteDeal",
    "uaDeleteInventory",
    "uaDeletePayments",
    "uaEditContacts",
    "uaEditDealWashout",
    "uaEditDeals",
    "uaEditExpenses",
    "uaEditInsuranceOnly",
    "uaEditPaidComissions",
    "uaEditInventory",
    "uaEditPayments",
    "uaEditSettings",
    "uaLocationAdmin",
    "uaManager",
    "uaPrintDealsForms",
    "uaSalesPerson",
    "uaUndeleteDeleted",
    "uaViewAccounts",
    "uaViewContacts",
    "uaViewCostsAndExpenses",
    "uaViewDeals",
    "uaViewDeleted",
    "uaViewInventory",
    "uaWebSiteAdmin",
] as const;

export type PermissionKey = (typeof PERMISSION_KEYS)[number];
