import { MS_IN_SECOND, SECONDS_IN_MINUTE } from "common/constants/time";

interface AppSettings {
    ROWS_PER_PAGE: Array<number>;
    TOAST_LIFETIME: number;
    DEFAULT_MAX_COLUMN_WIDTH: number;
    DEFAULT_FILTER_THRESHOLD: number;
    DEBOUNCE_TIME: number;
    DEFAULT_CARD_HEIGHT: number;
    BASE_CARD_WIDTH: number;
    BASE_CARD_HEIGHT: number;
    ROUTE_RESTORE_TIMEOUT_HOURS: number;
    INACTIVITY_TIMEOUT_SECONDS: number;
}

const {
    ROWS_PER_PAGE,
    TOAST_LIFETIME,
    DEFAULT_MAX_COLUMN_WIDTH,
    DEFAULT_FILTER_THRESHOLD,
    DEBOUNCE_TIME,
    DEFAULT_CARD_HEIGHT,
    BASE_CARD_WIDTH,
    BASE_CARD_HEIGHT,
    ROUTE_RESTORE_TIMEOUT_HOURS,
    INACTIVITY_TIMEOUT_SECONDS,
}: AppSettings = {
    ROWS_PER_PAGE: [10, 20, 50, 100, 1000],
    TOAST_LIFETIME: 3 * MS_IN_SECOND,
    DEFAULT_MAX_COLUMN_WIDTH: 350,
    DEFAULT_FILTER_THRESHOLD: 15,
    DEFAULT_CARD_HEIGHT: 983,
    BASE_CARD_WIDTH: 1670,
    BASE_CARD_HEIGHT: 1000,
    DEBOUNCE_TIME: 1000,
    ROUTE_RESTORE_TIMEOUT_HOURS: 8,
    INACTIVITY_TIMEOUT_SECONDS: 10 * SECONDS_IN_MINUTE,
};

export {
    ROWS_PER_PAGE,
    TOAST_LIFETIME,
    DEFAULT_MAX_COLUMN_WIDTH,
    DEFAULT_FILTER_THRESHOLD,
    DEBOUNCE_TIME,
    DEFAULT_CARD_HEIGHT,
    BASE_CARD_WIDTH,
    BASE_CARD_HEIGHT,
    ROUTE_RESTORE_TIMEOUT_HOURS,
    INACTIVITY_TIMEOUT_SECONDS,
};
