export interface TestDrive {
 inventoryUID: string;
 contactUID: string;
 managerName: string;
 dealersName: string;
 salesPerson: string;
 customerName: string;
 customerLastName: string;
 streetAddress: string;
 homePhone: string;
 workPhone: string;
 dlState: string;
 dlNumber: string;
 dlIssuingDate: string;
 dlExpirationDate: string;
 insCompany: string;
 insAgent: string;
 insPhone: string;
 vclMake: string;
 vclModel: string;
 vclYear: string;
 vclVIN: string;
 milesAllowed: string;
 returnTime: string;
 comments: string;
 outDate: string;
 outTime: string;
 outOdometer: string;
}
